### ISSUE TITLE
Restrict WP admin area setting does not work WP Customer Area 6.1.1

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#118]
With the setting checked, the user is still able to access the admin area.

When they do, there are a whole slew of menu index errors for whatever reason.

**Comment by ssteinerx** [comment]
Any progress on this?  This is holding up the deployment of the site I've been working on and I'd love to get this delivered so I can move on from this unexpected extra month of development...

**Comment by ssteinerx** [comment]
Please fix this or let me know what I'm looking for and I'll fix it myself.  It's been a week and my deployment (and paycheck) are being held up.

**Comment by vpratfr** [comment]
Hi,

sorry, May is a month full of "holiday" here in France this year, I did not get time to have a look at this.

Most of that happens in the `src\php\core-addons\admin-area` files, the menu is built and handled in `admin-menu-helper.class.php`.

I don't really know where that error could be coming from. I did not have a look at it and some other projects have stacked up since then.

**Comment by ssteinerx** [comment]
I have done substantial work on this plugin, reporting bugs, fixing bugs, etc.  Now I look like an idiot to my client for relying on it.  Please fix this bug now.  I do not have any more time to devote to supporting/debugging/fixing your product.

**Comment by vpratfr** [comment]
Should be fixed in latest develop
