### ISSUE TITLE
dropdown position and ajax

### ISSUE THREAD

**Issue by firebird631** [marvinlabs/customer-area#224]
Using AJAX, the dropdown top position when opened the first time after each new search (with or empty results) is incorrect. It seams to uses the height of the previous list of results. That means if the previous results had 2 entries, the top of the dropdown will be offset by the height of two entries.

For the first opening (then there is no previous results), there is an offset of one entry, I suppose it is the text of the status (select X mores characters, searching or no results).

**Comment by vpratfr** [comment]
Hi,

Thanks for the report. Can you paste a screenshot to explain that please?

**Comment by firebird631** [comment]
![issue_select2](https://cloud.githubusercontent.com/assets/7570462/16187651/d4633494-36d1-11e6-8b95-dd63c0e3aafe.png)

**Comment by tlartaud** [comment]
@firebird631 Hi,
I really do not understand the problem you are explaining there. However, I had already opened an issue about Select2, and closed it some minutes ago. I fixed that issue by just updating the select2 library. You can see some details in that issue : https://github.com/marvinlabs/customer-area/issues/223

I don't know if your problem is the same, or if it could be fixed by this issue. We will release that fix in the next 7.0.5 version, probably today or tomorrow. Once it get released, could you please try it again and come back to tell us if it get fixed or not ?

Best regards.

**Comment by firebird631** [comment]
I'm sorry I don't explain how I've done to post this issue here in place of select2 issue page. Sorry for the convenience, you can delete this issue.

Best regards.
