### ISSUE TITLE
Make the file upload process extendable

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#76]
Following #74, in order to support external storage of files, we need the file selection to be abstracted (currently two methods are available: direct upload or copy from a path on the server)

Basically we require:

- A hook to append to the file upload methods
- A hook to present the file selection control (possibly with Ajax retrieval of the file list)
- A way to be able to change the way files are streamed during a download (maybe we should hardcode 2 cases: local file or remote file)

This is still a rougth idea of what would need to be done

**Comment by ssteinerx** [comment]
This error from file.php is coming around line 291.  The function's looking for the file in its temporary location and it's no longer there.

This seems to be an issue involving a change to the order in which things are done.  I.E. it seems that Customer Area has moved the file out of the way (possibly via wp_handle_upload action), before WordPress gets a crack at it.  I'm guessing since I'm not sure where in Customer Area those hooks are called, but that seems like a logical explanation if CustomerArea is firing that filter itself.

**Comment by vpratfr** [comment]
@ssteinerx The function is using a function which simply moves file using PHP functions, nothing with wp_handle_upload).

**Comment by ssteinerx** [comment]
I'm not calling the function, this is trying to just upload via the normal CustomerArea "add private file" menu item.

**Comment by vpratfr** [comment]
@ssteinerx Right, fixed. This was a regression due to WP's `save_post` hook madness introduced with logging

**Comment by vpratfr** [comment]
Please open a new issue when you notice a bug, this makes it easy to track problems and mark them as resolved.

**Comment by ssteinerx** [comment]
Will do.  Not sure how to interleave working on a branch and bug reporting in main area.  I'll just prefix the bug with the branch, I guess.

**Comment by ssteinerx** [comment]
Confirmed, upload issue is fixed in 7463e2a.

**Comment by vpratfr** [comment]
Marking as closed. This is now implemented and will be available in next release. 

We currently provide 2 methods for upload (ajax upload with progress + move/copy from server's FTP upload folder) but the door is now open for cloud storage add-ons.

+ support for multiple attachments has been added.
